name: Deploy Codespace Templates
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo chmod +x ./scripts/deploy_templates.sh
          ./scripts/deploy_templates.sh
