name: Deploy Codespace Templates

on:
  push:
    branches: [ main ]
    paths:
      - 'templates/**'
      - '.github/workflows/deploy.yml'
      - 'scripts/deploy_templates.sh'

# Allow the workflow to create commits
permissions:
  contents: write

jobs:
  deploy:
    name: Deploy Templates
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for proper git diff
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions@users.noreply.github.com'
      
      - name: Make script executable
        run: chmod +x ./scripts/deploy_templates.sh
      
      - name: Run deployment
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions@users.noreply.github.com
        run: |
          ./scripts/deploy_templates.sh
      
      - name: Show deployment status
        if: always()
        run: |
          echo "Deployment completed with status: ${{ job.status }}"
